appName: "Kava Json Rpc Proxy"
appVersion: "0.1.0"
http:
  port: ":8080"
  jsonRpcEndpoint: "/"
  maxRequestBodySize: 1048576 # 1 MB
  requestTimeout: 30
  maxPoolWorkers: 1000
redis:
  url: "redis://localhost:6379"
  defaultTTL: 30
nodes:
  - name: "Node 1"
    url: "http://localhost:8545"
    timeout: 5000
    rps: 100
    token_bucket_capacity: 50
    whitelisted_methods:
      - "eth_getBlockByNumber"
      - "eth_getBlockByHash"
    blacklisted_methods:
    cached_methods:
      - "eth_getBlockByNumber"
      - "eth_getBlockByHash"

