version: '3.8'

volumes:
  redis_volume:

services:
  redis:
    hostname: drivers
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - type: volume
        target: /data
        source: redis_volume



