version: '3.8'

volumes:
  redis_volume:

services:
  redis:
    hostname: drivers
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - type: volume
        target: /data
        source: redis_volume

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: maximussxgod/json-rpc-node-proxy:v3
    container_name: json-rpc-node-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/build/config.yaml
    depends_on:
      - redis
